version: '3.4'
services:
  app:
    build:
      context: .
    container_name: jurata_2
    env_file:
      - .env
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
